name: 'facebook_ads_source'
version: '0.3.0'
config-version: 2
require-dbt-version: [">=0.20.0"]
models:
  facebook_ads_source:
    +schema: stg_facebook_ads
    +materialized: table
    tmp:
      +materialized: view
vars:
  facebook_ads_source:
    account_history: "{{ source('facebook_ads','account_history') }}"
    ad_history: "{{ source('facebook_ads','ad_history') }}"
    ad_set_history: "{{ source('facebook_ads','ad_set_history') }}"
    basic_ad: "{{ source('facebook_ads','basic_ad') }}"
    campaign_history: "{{ source('facebook_ads','campaign_history') }}"
    creative_history: "{{ source('facebook_ads','creative_history') }}"
