name: 'facebook_ads_source_integration_tests_2'
version: '0.7.2'
profile: 'integration_tests'
config-version: 2

vars:
  facebook_ads_schema: facebook_ads_source_integration_tests_2
  facebook_ads_source:
    facebook_ads_account_history_identifier: "facebook_ads_account_history_data"
    facebook_ads_ad_history_identifier: "facebook_ads_ad_history_data"
    facebook_ads_ad_set_history_identifier: "facebook_ads_ad_set_history_data"
    facebook_ads_basic_ad_identifier: "facebook_ads_basic_ad_data"
    facebook_ads_campaign_history_identifier: "facebook_ads_campaign_history_data"
    facebook_ads_creative_history_identifier: "facebook_ads_creative_history_data"

seeds:
  facebook_ads_source_integration_tests_2:
    +column_types:
      id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      account_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      campaign_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      ad_set_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      ad_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      creative_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      page_link: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
      template_page_link: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
      _fivetran_synced: "timestamp"
      updated_time: "timestamp"
        
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
